# Generated by Django 6.0 on 2026-02-05 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SN', models.CharField(max_length=100, verbose_name='料號')),
                ('ItemName', models.CharField(max_length=255, verbose_name='品名')),
                ('Spec', models.TextField(blank=True, null=True, verbose_name='規格')),
                ('Location', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('Quantity', models.IntegerField(default=0, verbose_name='數量')),
                ('UpdateTime', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '物料清單',
                'verbose_name_plural': '物料清單',
                'db_table': 'material_app_itemlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DeptID', models.CharField(blank=True, max_length=50, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('LastSync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialOverview',
            fields=[
                ('BoxID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='箱子編號')),
                ('Category', models.CharField(blank=True, max_length=50, null=True, verbose_name='類別')),
                ('Description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('Owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='負責人')),
                ('Status', models.CharField(blank=True, max_length=20, null=True, verbose_name='狀態')),
                ('Locked', models.BooleanField(default=False, verbose_name='是否鎖定')),
                ('CreateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
            ],
            options={
                'verbose_name': '物料箱總覽',
                'verbose_name_plural': '物料箱總覽',
                'db_table': 'material_app_materialoverview',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False, verbose_name='記錄編號')),
                ('ActionType', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫'), ('MOVE', '移動'), ('ADJUST', '調整')], max_length=20, verbose_name='動作類型')),
                ('FromBoxID', models.CharField(blank=True, max_length=50, null=True, verbose_name='來源箱')),
                ('ToBoxID', models.CharField(blank=True, max_length=50, null=True, verbose_name='目的箱')),
                ('TransQty', models.IntegerField(verbose_name='異動數量')),
                ('StockBefore', models.IntegerField(verbose_name='異動前庫存')),
                ('StockAfter', models.IntegerField(verbose_name='異動後庫存')),
                ('Operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人員')),
                ('Remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('Timestamp', models.DateTimeField(auto_now_add=True, verbose_name='時間戳記')),
                ('SN', models.ForeignKey(db_column='SN_id', on_delete=django.db.models.deletion.CASCADE, to='material_app.materialitems', verbose_name='料號')),
            ],
            options={
                'verbose_name': '交易記錄',
                'verbose_name_plural': '交易記錄',
                'db_table': 'material_app_transactionlog',
                'ordering': ['-Timestamp'],
                'indexes': [models.Index(fields=['SN'], name='material_ap_SN_id_a56d56_idx')],
            },
        ),
    ]
