# Generated by Django 6.0 on 2026-02-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOverview',
            fields=[
                ('BoxID', models.CharField(help_text='編號唯一，不可重複', max_length=50, primary_key=True, serialize=False)),
                ('Category', models.CharField(blank=True, help_text='類別（如：一般物料、維修件）', max_length=50, null=True)),
                ('Description', models.CharField(blank=True, help_text='備註該編號的用途', max_length=255, null=True)),
                ('Owner', models.CharField(blank=True, help_text='負責人姓名', max_length=50, null=True)),
                ('Status', models.CharField(blank=True, help_text='狀態（使用中、空閒、結案）', max_length=20, null=True)),
                ('Locked', models.BooleanField(default=False, help_text='是否鎖定')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(help_text='產品唯一識別序號或條碼', max_length=100)),
                ('ItemName', models.CharField(help_text='商品名稱', max_length=255)),
                ('Spec', models.TextField(blank=True, help_text='規格型號', null=True)),
                ('Location', models.CharField(blank=True, help_text='實體存放位置', max_length=100, null=True)),
                ('Quantity', models.IntegerField(default=0, help_text='目前庫存數量')),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('BoxID', models.ForeignKey(help_text='關聯到容器', on_delete=django.db.models.deletion.CASCADE, to='material_app.materialoverview')),
            ],
            options={
                'unique_together': {('SN', 'BoxID')},
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionType', models.CharField(help_text='入庫、出庫、調撥', max_length=20)),
                ('FromBoxID', models.CharField(blank=True, help_text='來源位置', max_length=50, null=True)),
                ('ToBoxID', models.CharField(blank=True, help_text='目的位置', max_length=50, null=True)),
                ('TransQty', models.IntegerField(help_text='變動數量')),
                ('StockBefore', models.IntegerField(help_text='動作前的原始庫存')),
                ('StockAfter', models.IntegerField(help_text='動作後的剩餘庫存')),
                ('Operator', models.CharField(blank=True, help_text='誰執行的', max_length=50, null=True)),
                ('Remark', models.TextField(blank=True, help_text='異動原因', null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('SN', models.ForeignKey(help_text='哪件東西動了', on_delete=django.db.models.deletion.CASCADE, to='material_app.itemlist')),
            ],
        ),
    ]
