# Generated by Django 6.0.3 on 2026-03-26 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類名稱')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='BOMNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='節點名稱')),
                ('qty_required', models.IntegerField(default=1, verbose_name='需求數量（相對父節點）')),
                ('level', models.IntegerField(default=0, verbose_name='層級（0=根）')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='material_app.bomnode', verbose_name='父節點')),
            ],
            options={
                'verbose_name': 'BOM 節點',
                'verbose_name_plural': 'BOM 節點',
                'db_table': 'bom_node',
            },
        ),
        migrations.CreateModel(
            name='BOMRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_qty', models.IntegerField(default=1, verbose_name='生產數量')),
                ('status', models.CharField(choices=[('CHECKING', '檢查中'), ('CONFIRMED', '已確認'), ('DONE', '已完成'), ('FAILED', '失敗/取消')], default='CHECKING', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('bom_root', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='releases', to='material_app.bomnode', verbose_name='BOM 根節點（產品）')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_releases', to=settings.AUTH_USER_MODEL, verbose_name='建立人')),
            ],
            options={
                'verbose_name': 'BOM 批次出庫',
                'verbose_name_plural': 'BOM 批次出庫',
                'db_table': 'bom_release',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=100, verbose_name='料號')),
                ('item_name', models.CharField(max_length=255, verbose_name='品名')),
                ('spec', models.TextField(blank=True, null=True, verbose_name='規格')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('quantity', models.IntegerField(default=0, verbose_name='數量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='單價')),
                ('required_qty', models.IntegerField(blank=True, null=True, verbose_name='需求數量')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_app.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '物料清單',
                'verbose_name_plural': '物料清單',
                'db_table': 'material_items',
            },
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='借用數量')),
                ('status', models.CharField(choices=[('PENDING', '待審核'), ('APPROVED', '已核准'), ('REJECTED', '已拒絕'), ('RETURNED', '已歸還')], default='PENDING', max_length=20, verbose_name='狀態')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='預計歸還日')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='實際歸還日')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='審核人')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='borrow_requests', to='material_app.materialitems', verbose_name='物料')),
            ],
            options={
                'verbose_name': '借用申請',
                'verbose_name_plural': '借用申請',
                'db_table': 'borrow_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOMReleaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_qty', models.IntegerField(verbose_name='需求總量')),
                ('actual_qty', models.IntegerField(default=0, verbose_name='實際扣庫量')),
                ('is_shortage', models.BooleanField(default=False, verbose_name='是否缺料')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='material_app.bomrelease', verbose_name='出庫單')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_app.materialitems', verbose_name='物料')),
            ],
            options={
                'verbose_name': 'BOM 出庫明細',
                'verbose_name_plural': 'BOM 出庫明細',
                'db_table': 'bom_release_log',
            },
        ),
        migrations.AddField(
            model_name='bomnode',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_nodes', to='material_app.materialitems', verbose_name='對應物料'),
        ),
        migrations.CreateModel(
            name='MaterialOverview',
            fields=[
                ('box_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='箱子編號')),
                ('box_type', models.CharField(blank=True, choices=[('project', '專案'), ('personal', '個人'), ('warehouse', '倉庫'), ('spare', '備品'), ('test', '測試'), ('other', '其他')], max_length=20, null=True, verbose_name='箱子類型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='狀態')),
                ('is_locked', models.BooleanField(default=False, verbose_name='是否鎖定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='鎖住時間')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boxes', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
            ],
            options={
                'verbose_name': '物料箱總覽',
                'verbose_name_plural': '物料箱總覽',
                'db_table': 'material_overview',
            },
        ),
        migrations.AddField(
            model_name='materialitems',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='material_app.materialoverview', verbose_name='所屬箱子'),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫'), ('MOVE', '移動'), ('ADJUST', '調整'), ('BORROW', '借用'), ('RETURN', '歸還')], max_length=20, verbose_name='動作類型')),
                ('from_box_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='來源箱（快照）')),
                ('to_box_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='目的箱（快照）')),
                ('trans_qty', models.IntegerField(verbose_name='異動數量')),
                ('stock_before', models.IntegerField(verbose_name='異動前庫存')),
                ('stock_after', models.IntegerField(verbose_name='異動後庫存')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='時間戳記')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_app.materialitems', verbose_name='物料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
            ],
            options={
                'verbose_name': '交易記錄',
                'verbose_name_plural': '交易記錄',
                'db_table': 'transaction_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='materialitems',
            unique_together={('sn', 'box')},
        ),
        migrations.CreateModel(
            name='BoxPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True, verbose_name='可讀')),
                ('can_write', models.BooleanField(default=False, verbose_name='可寫')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_permissions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='material_app.materialoverview', verbose_name='箱子')),
            ],
            options={
                'verbose_name': '箱子權限',
                'verbose_name_plural': '箱子權限',
                'db_table': 'box_permission',
                'unique_together': {('user', 'box')},
            },
        ),
    ]
