# Generated by Django 6.0 on 2026-02-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.CharField(help_text='打工號，唯一', max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='員工姓名', max_length=50)),
                ('Password', models.CharField(help_text='密碼（存儲為 hash）', max_length=255)),
                ('IsActive', models.BooleanField(default=True, help_text='帳號是否啟用')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('Token', models.CharField(help_text='隨機生成的 token 字串', max_length=128, primary_key=True, serialize=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ExpiresAt', models.DateTimeField(help_text='過期時間（login 時設為當前 + 24h）')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='material_app.employee')),
            ],
        ),
    ]
