# Generated by Django 6.0 on 2026-02-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DeptID',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部門'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='工號'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='是否在職'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='LastSync',
            field=models.DateTimeField(auto_now=True, verbose_name='最後同步時間'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='SN',
            field=models.ForeignKey(blank=True, db_column='SN_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material_app.materialitems', verbose_name='料號'),
        ),
    ]
