[gcp_service_account]
type = "service_account"
project_id = "material202601"
private_key_id = "f252b751f9e58a400e81b691e5d4061370c6283d"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCXVLeRr0UnfT/1
9ekSg3wuwlzQ1+TuD/eF81ebvJWO3wRiLTXPFeBrKxh/yb6WxlJu+eHjgtZEFZii
bUDb/JUQGEB6uhvLnVfelsPj6SV+Zjjr6YMXlLUxR6IMl15XwI51N8uq39/C0/p7
99+y11E1CMCO6J8pjZaFuJHOTwSw8GaXj50VAjV6gfQVYgmhdxwKZBkz8ZsJyqyZ
W58tNozg4q0cNxABwo+QdW7jFFgiS3cNVyiyBK2H0Sr73cjrFkdv6HT06gUlsscp
14vI0OWowCmwPYq4umobbbIa2otw8h+pRP+OwaH/QbyX6dttc53C2LFJaJOaZiHt
nhriidMDAgMBAAECggEAFsaV0DPQVSapIzQNDY/Dd2giPv5XQqsdhkf/Bf3mhnez
ObFzOUUiHw7/42+yIxAbJP+vyyWMaPfVHpER42oK5z63KaFsAIOgT2xidCFJVtI8
u+jLpZdog8+zqHB5rvxYlHS+zutdyn1L5C+Et+5nFvPHw1poZgEcx+hk7WeAHb79
bM6x6FqPlEyIpdYVgEdxrDWNSSf4grbXm5k1fZ422McLf2+rvO9UXk6AQtUM3pBD
sXmoqnK6/x/+friuROnh3wy1Ir7BZAH1mtsjCwc5MucraCvoxVcY9YZKnnUA2Xel
Ahc6xJ7ixtiFmgjC455HrLwBd/gkBdaRXfx50Rs+0QKBgQDNaPYpY+z8oZuK7XxV
flIh8txSnB5tbSEmxrPuo1EyzlYQ6mpfKRfjKDT0RLH36/EUcu54OFC2gU8qUrx2
YTcz7apeVg0dx3IF7WvADhQ+RQVnEWQWp+ZgzBryztL1+q6tt0IGY+ZMNYlm2Vgo
wQ+qCMz5tI9EdZcQ10GgFz/psQKBgQC8mhYAO51ang8LJyAoK1+VOsiOyTWRBmdb
YE4lITeMyY5ARyfTIRPObgRhTfuaycUW6g2wpC4K1RCu34aYo3v9BWnUWPiKo8Ms
EZB1d1OmYxWG+1D5bODm5C1vK3DcAaarPwz7ezG6AR/reSHMTm57XQiwLBGQtG/9
rBHQd48A8wKBgQDEJ4+rRvlw5wMaUF+DZPYZ5UnwuZV0+dnGpcn+AYfw9InL7Y9X
AG8HRcYL3e31yyKVXIvN0jmBj0qCKDBA++UzeapQG+y6m1OPxYI4DTnXnSHjov/p
grzFgyPY6xkaPSHCUlaCs7Og4x8rUDKX+IV04qKbcom93m08b9MDhjBKgQKBgDJu
7dUwG9rgi1tLIiE7v/qS1pDAI2/di4P2086//C/MshpkLLUbkkVQTCGNDewNaoO/
INwMezdwVF6+7SoiBYTajrs283d3ZTiCleOjfh3vPxFyYOvh/p4fhDrHHg3m7x+5
44nYHqsDo/p+0NfmXUrlzO33StcsOQpXmgfqALabAoGAa1am+eoaPbdDZdAysqNL
chx+Aba1dqQV0miDt7Xv5w0J0m5c+XLGL08W0xXg9YeZyukxanw5R6GXTQHdNEBd
2QnmKkzDNe7NIl9OX7x+IO05jdEjH/NPUVzTIuhCVZxcShoEyKPeoYMCTJrAqiTM
9dOlRrMT5c2HMcRnIIl8QCk=
-----END PRIVATE KEY-----"""
client_email = "inventory-system@material202601.iam.gserviceaccount.com"
client_id = "103049071559053791262"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inventory-system%40material202601.iam.gserviceaccount.com"
universe_domain = "googleapis.com"